name: Create Release from Local Build

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Verify zip file exists
        run: |
          if [ ! -f "ov25-woo-extension.zip" ]; then
            echo "❌ Error: ov25-woo-extension.zip not found!"
            echo "Please build and commit the zip file locally before creating a release tag."
            exit 1
          fi
          echo "✅ Found ov25-woo-extension.zip"
          ls -la ov25-woo-extension.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ov25-woo-extension.zip
          name: "Release v${{ steps.version.outputs.version }}"
          body: |
            ## OV25 WooCommerce Extension v${{ steps.version.outputs.version }}
            
            ### Installation
            1. Download the `ov25-woo-extension.zip` file
            2. Upload to WordPress admin → Plugins → Add New → Upload Plugin
            3. Activate the plugin
            
            ### Update
            If you have the plugin installed, you should receive an automatic update notification.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 